AspNetCorePlayground/Models/ErrorViewModel.cs
using System;

namespace AspNetCorePlayground.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetCorePlayground/Models/MyFirstModelBinderTest.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;

namespace AspNetCorePlayground.Models
{
    public class MyFirstModelBinderTest
    {
        [ModelBinder(BinderType = typeof(MyFirstModelBinder))]
        public decimal SomeDecimal { get; set; }
    }
}

AspNetCorePlayground/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCorePlayground.Models;
using AspNetCorePlayground.Filters;

namespace AspNetCorePlayground.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [TypeFilter(typeof(MyActionFilter))]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

    [HttpGet("test")]
    public IActionResult TestMyFirstModelBinder(MyFirstModelBinderTest model)
    {
        return Json(model);
    }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspNetCorePlayground/ViewComponents/MyFirstViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCorePlayground.ViewComponents
{
    public class MyFirstViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync() {
            await Task.Delay(0);
            return View();
        }
    }
}

AspNetCorePlayground/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1 class="page-header">TagHelper</h1>
<h2>TagHelper Structure</h2>
<!-- Index.cshtml -->
<my-first 
    my-string-property="My Property Value" 
    my-date-time-property="new DateTime()">
    This is the original Inner HTML from the *.cshtml file.
</my-first>

<vc:my-first>
    This is the original Inner HTML from the *.cshtml file.
</vc:my-first>

@Url.Action("Index", "Home")

AspNetCorePlayground/Views/Shared/Components/MyFirst/Default.cshtml
<p>My first view component</p>